name: Release Pls
permissions: write-all
on:
  push:
    tags:
      - '*'
env:
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get release version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"

      - name: Download APK from dev release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEV_RELEASE="${RELEASE_VERSION}-${SHORT_SHA}"

          echo "Looking for dev release: $DEV_RELEASE"

          gh release download "$DEV_RELEASE" \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "bunny-launcher.apk" \
            --dir .

      - name: Get build tools
        run: |
          BUILD_TOOLS_PATH=/usr/local/lib/android/sdk/build-tools/$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOLS=$BUILD_TOOLS_PATH" >> $GITHUB_ENV

      - name: Verify the APK signature
        run: $BUILD_TOOLS/apksigner verify bunny-launcher.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Upload release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bunny-launcher.apk
          asset_name: bunny-launcher.apk
          asset_content_type: application/vnd.android.package-archive

